CREATE SCHEMA IF NOT EXISTS u812598544_sinte;

DROP TABLE IF EXISTS u812598544_sinte.ghl_registros2;

CREATE TABLE u812598544_sinte.ghl_registros2
(
    import_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text,
    firma text,
    tipo_de_arquivo text,
    n_do_arquivo text,
    disquete numeric,
    "Data" text
);
